package com.klabs.accountservice.domain.model;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

@Getter
@AllArgsConstructor
@NoArgsConstructor
public class DeletedAccount {

    private Long id;

    private UUID originalUuid;

    private String originalLogin;

    private String originalEmail;

    private String accountDataJson;

    private LocalDateTime deletedAt;

    private LocalDateTime purgeAt;

    /**
     * Creates DeletedAccount from Account entity when account is marked as deleted.
     * Serializes all account data to JSON for potential restoration within 60 days.
     *
     * @param account the account to be marked as deleted
     * @return DeletedAccount with serialized account data
     * @throws JsonProcessingException if JSON serialization fails
     */
    public static DeletedAccount fromAccount(Account account) throws JsonProcessingException {
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime purgeAt = now.plusDays(60);

        // Create map with account data for JSON serialization
        Map<String, Object> accountData = new HashMap<>();
        accountData.put("uuid", account.getUuid().toString());
        accountData.put("login", account.getLogin().getValue());
        accountData.put("email", account.getEmail().getValue());
        accountData.put("hasPassword", account.hasPassword());
        if (account.getPassword() != null) {
            accountData.put("passwordHash", account.getPassword().getHashedValue());
        }
        accountData.put("accountStatus", account.getAccountStatus().name());
        accountData.put("registerDate", account.getRegisterDate().toString());
        if (account.getLastLogInDate() != null) {
            accountData.put("lastLogInDate", account.getLastLogInDate().toString());
        }
        accountData.put("emailVerified", account.isEmailVerified());

        // Serialize OAuth providers if any
        if (account.getOAuthProviders() != null && !account.getOAuthProviders().isEmpty()) {
            accountData.put("oauthProviders", account.getOAuthProviders().stream()
                    .map(provider -> Map.of(
                            "providerName", provider.getProviderName(),
                            "providerUserID", provider.getProviderUserID(),
                            "linkedAt", provider.getLinkedAt().toString()
                    ))
                    .toList());
        }

        // Serialize to JSON
        ObjectMapper objectMapper = new ObjectMapper();
        String json = objectMapper.writeValueAsString(accountData);

        // Create and return DeletedAccount
        return new DeletedAccount(
                null,  // id will be generated by database
                account.getUuid(),
                account.getLogin().getValue(),
                account.getEmail().getValue(),
                json,
                now,
                purgeAt
        );
    }

    public boolean canBeRestored() {
        return LocalDateTime.now().isBefore(purgeAt);
    }

    public boolean shouldBePurged() {
        LocalDateTime now;
        return (now = LocalDateTime.now()).isAfter(purgeAt) || now.isEqual(purgeAt);
    }
}
